DROP DATABASE IF EXISTS DATA_PROJECT;

CREATE DATABASE DATA_PROJECT ;

USE DATA_PROJECT ;

DROP TABLE IF EXISTS DEPARTEMENT ;
CREATE TABLE DEPARTEMENT (ID_DEPT INT(10) AUTO_INCREMENT NOT NULL,
NUMDEPT VARCHAR(3) NOT NULL,
NOMDEPT VARCHAR(255),
NOMDEPTMAJ VARCHAR(255),
SLUGDEPT VARCHAR(255),
PRIMARY KEY (ID_DEPT)) ENGINE=InnoDB;

DROP TABLE IF EXISTS PHOTOS ;
CREATE TABLE PHOTOS (ID_PHOTO INT(10) AUTO_INCREMENT NOT NULL,
NUMDEPT VARCHAR(3) NOT NULL,
COMMUNE VARCHAR(255),
EDIFICE VARCHAR(255),
LEGENDE VARCHAR(255),
AUTEUR VARCHAR(255),
DATE VARCHAR(255),
MINIATURE VARCHAR(255),
IMAGE VARCHAR(255),
PRIMARY KEY (ID_PHOTO)) ENGINE=InnoDB;

DROP TABLE IF EXISTS VILLE ;
CREATE TABLE VILLE (ID_VILLE INT(10) AUTO_INCREMENT NOT NULL,
NUMDEPT VARCHAR(3) NOT NULL,
NOMVILLE VARCHAR(255),
SLUGVILLE VARCHAR(255),
GPS_LAT FLOAT(4),
GPS_LNG FLOAT(4),
PRIMARY KEY (ID_VILLE)) ENGINE=InnoDB;

DROP TABLE IF EXISTS PREFECTURE ;
CREATE TABLE PREFECTURE (ID_PREF INT(10) AUTO_INCREMENT NOT NULL,
NUMDEPT VARCHAR(3) NOT NULL,
NOMDEPT VARCHAR(255),
PREFECTURE VARCHAR(255),
REGION VARCHAR(255),
PRIMARY KEY (ID_PREF)) ENGINE=InnoDB;

ALTER TABLE `VILLE` ADD INDEX(`NUMDEPT`);
ALTER TABLE `DEPARTEMENT` ADD INDEX(`NUMDEPT`);
ALTER TABLE `PHOTOS` ADD INDEX(`NUMDEPT`);
ALTER TABLE `PREFECTURE` ADD INDEX(`NUMDEPT`);

ALTER TABLE VILLE ADD CONSTRAINT FK_VILLE_NUMDEPT FOREIGN KEY (NUMDEPT) REFERENCES DEPARTEMENT (NUMDEPT);
ALTER TABLE DEPARTEMENT ADD CONSTRAINT FK_DEPARTEMENT_NUMDEPT FOREIGN KEY (NUMDEPT) REFERENCES PREFECTURE (NUMDEPT);
ALTER TABLE PHOTOS ADD CONSTRAINT FK_PHOTOS_NUMDEPT FOREIGN KEY (NUMDEPT) REFERENCES DEPARTEMENT (NUMDEPT);

